version: "3.4"

services:
  selenium_standalone_chrome_host:
    image: "selenium/standalone-chrome:103.0"
    ports:
      - "4444:4444"
    networks:
      default_network:
  
  test_runner_demo_chrome:
    image: "smokey_demo"
    environment:
      REMOTE_HOST: "http://selenium_standalone_chrome_host:4444/"
    networks:
      default_network:
    depends_on:
      - selenium_standalone_chrome_host

networks:
  default_network: