name: "Nuget"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CORE_PROJECT_PATH: 'src/Smokey.Core/Smokey.Core.csproj'
  EXTENSIONS_PROJECT_PATH: 'src/Smokey.Core/Smokey.Core.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\packages
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  smokey_core:
    name: 'Smokey.Core'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: 'Restore packages'
        run: dotnet restore ${{ env.CORE_PROJECT_PATH }}

      - name: 'Build project'
        run: dotnet build ${{ env.CORE_PROJECT_PATH }} --no-restore --configuration Release

      - name: 'Get Version'
        id: version
        uses: battila7/get-version-action@v2

      - name: 'Pack project'
        run: dotnet pack ${{ env.CORE_PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Push package'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}